### ISSUE TITLE
Codacy: condition is always true/false

### ISSUE THREAD

**Issue by mihalicyn** [checkpoint-restore/criu#2120]
https://app.codacy.com/gh/mihalicyn/criu/issues?&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W119LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjIyMzciXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W119XQ==

**Comment by Daz-3ux** [comment]
I want to work on this issue, can I have a try? :)

**Comment by TaeminHa** [comment]
Hi! I'm a student from UT Austin, and would be happy to take on this issue! Can you assign this to me?

**Comment by mihalicyn** [comment]
Feel free to take :)

**Comment by Jayanth19524** [comment]
is this issue solved??

**Comment by mihalicyn** [comment]
@TaeminHa ?

**Comment by TaeminHa** [comment]
Hi, this issue is resolved. I'll create a separate PR to put the changes in separate commits as discussed.

**Comment by Snorch** [comment]
No this issue is NOT resolved, we have really-really draft PR #2141, which from the first glance tries to do the right thing in code. But it is not ready to review as it has bad commit structure: no signed-offs, no rebase to latest criu-dev, empty commits, bad commit subject and description format/wording, fixup commits.

Read https://github.com/checkpoint-restore/criu/blob/criu-dev/CONTRIBUTING.md it contains all the information about how the right PR should look like.

**Comment by vishisht-dubey** [comment]
Hii @Snorch i would like to contibute to this issue can u assign this to me?

**Comment by Min2who** [comment]
i have seen the issue and i guess i can solve the issue can you assign me this issue

**Comment by Snorch** [comment]
No real need to assign, comment that you are working on this is enough, @vishisht-dubey @Min2who please communicate with each other not to do the same thing twice =)

**Comment by rohitsinghnaruka** [comment]
Hii , @Snorch  & @mihalicyn 
i'm Working on this .

**Comment by AtriChatterjee1** [comment]
HI ! @Snorch and @mihalicyn ! I am a new contributor to criu, and would love to work on this

**Comment by AtriChatterjee1** [comment]
Hey @Snorch Can't find the issue on codacy for some reason, mind sharing it again

**Comment by Jayantbhoj** [comment]
hi is this issue resolved?

**Comment by Goyamjain06** [comment]
Opened #3130 addressing the redundant `!ret` check in `criu/kerndat.c`'s `root_only_init()` — one of the conditions originally identified in the abandoned #2141. Kept this scoped to just this one fix (clean, rebased, single commit) rather than reviving the full multi-file PR, to make it easier to review. Happy to pick up more of the Codacy pattern 2237 instances in follow-up PRs if this approach looks good.
